//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acct.common.POCO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    [Serializable]
    public partial class Customer
    {
        public Customer()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "Name is required")]
        [Index(IsUnique = true)]
        [MaxLength(255)]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        [MaxLength(255)]
        public string Phone { get; set; }
        [MaxLength(255)]
        public string Fax { get; set; }
        [MaxLength(255)]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [MaxLength(255)]
        [DisplayName("Contact Name")]
        public string ContactName { get; set; }

        [DisplayName("GST")]
        public int idmas_GST { get; set; }

        [ForeignKey("idmas_GST")]
        public virtual GST GST { get; set; }
        public ICollection<Order> Order { get; set; }
    }
}
