//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace acct.common.POCO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Serializable]
    public partial class GST
    {
        public GST()
        {
            //this.Customer = new HashSet<Customer>();
        }
        
        public int Id { get; set; }

        [DisplayName("Code")]
        [Required(ErrorMessage = "Code is required")]
        [MaxLength(45)]
        [Index(IsUnique = true)]
        public string Code { get; set; }

        [Required]
        [Range(0, 100, ErrorMessage = "GST Rate must be between 0 and 100")]
        public decimal Rate { get; set; }
    
        //public ICollection<Customer> Customer { get; set; }
    }
}
