//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acct.common.POCO
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Serializable]
    public partial class Payment
    {
        public Payment()
        {
        }
        public Payment(decimal amount, DateTime date ){
            Amount = amount;
            Date = date;
        }
        public int Id { get; set; }
        [Required(ErrorMessage = "Required")]
        public int CustomerId { get; set; }
        [Range(0.0, Double.MaxValue, ErrorMessage = "Amount must be positive")]
        public decimal Amount { get; set; }

        [DisplayName("Payment Method")]
        public string PaymentMethod { get; set; }
        [DisplayName("Reference Number")]
        public string ReferenceNumber { get; set; }

        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
        [DisplayName("Payment Date")]
        public DateTime Date { get; set; }

        public virtual ICollection<PaymentDetail> PaymentDetail { get; set; }
    }
}
