//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acct.common.POCO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Serializable]
    [Table("Quotation")]
    public partial class Quotation : Order
    {
        //public int Id { get; set; }

        //[DisplayName("Quotation Number")]
        //[Required(ErrorMessage = "Required")]
        //[MaxLength(12)]
        //[Index(IsUnique = true)]

        //public string QuotationNumber { get; set; }

        //public int ar_order_Id { get; set; }
    
        //public virtual Order Order { get; set; }
    }
}
