//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace acct.common.POCO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Serializable]
    public partial class UnitMeasure
    {
        public int Id { get; set; }
        [DisplayName("Code")]
        [Required(ErrorMessage = "Code is required")]
        [Index(IsUnique = true)]
        [MaxLength(2)]
        public string Code { get; set; }
        public string Description { get; set; }
    }
}
